package org.sunbird.content.util

object ContentConstants {
    val CHILDREN: String = "children"
    val REQUIRED_KEYS: List[String] = List("createdBy", "createdFor", "organisation", "framework")
    val CONTENT_TYPE: String = "contentType"
    val CONTENT_TYPE_ASSET_CAN_NOT_COPY: String = "CONTENT_TYPE_ASSET_CAN_NOT_COPY"
    val STATUS: String = "status"
    val ERR_INVALID_REQUEST: String = "ERR_INVALID_REQUEST"
    val MIME_TYPE: String = "mimeType"
    val CONTENT_SCHEMA_NAME: String = "content"
    val SCHEMA_NAME: String = "schemaName"
    val RESPONSE_SCHEMA_NAME: String = "responseSchemaName"
    val SCHEMA_VERSION: String = "1.0"
    val ARTIFACT_URL: String = "artifactUrl"
    val IDENTIFIER: String = "identifier"
    val MODE: String = "mode"
    val COLLECTION_MIME_TYPE: String = "application/vnd.ekstep.content-collection"
    val ORIGIN: String = "origin"
    val ORIGIN_DATA: String = "originData"
    val ERR_INVALID_UPLOAD_FILE_URL: String = "ERR_INVALID_UPLOAD_FILE_URL"
    val ROOT_ID: String = "rootId"
    val HIERARCHY: String = "hierarchy"
    val ROOT: String = "root"
    val NODES_MODIFIED: String = "nodesModified"
    val VISIBILITY: String = "visibility"
    val METADATA: String = "metadata"
    val END_NODE_OBJECT_TYPES = List("Content", "ContentImage")
    val VERSION_KEY: String = "versionKey"
    val H5P_MIME_TYPE = "application/vnd.ekstep.h5p-archive"
    val COPY_TYPE: String = "copyType"
    val COPY_TYPE_SHALLOW: String = "shallow"
    val COPY_TYPE_DEEP: String = "deep"
    val CONTENT: String = "content"
    val IMAGE_SUFFIX: String = ".img"
    val ERR_INVALID_CONTENT_ID: String = "ERR_INVALID_CONTENT_ID"
    val EDIT_MODE: String = "edit"
    val CONTENT_IMAGE_OBJECT_TYPE = "ContentImage"
    val ERR_CONTENT_NOT_DRAFT = "ERR_CONTENT_NOT_DRAFT"
    val COLLECTION_SCHEMA_NAME: String = "collection"
    val IDENTIFIERS: String = "identifiers"
    val PACKAGE_VERSION: String = "pkgVersion"
    val CHANNEL: String = "channel"
    val ERR_CONTENT_RETIRE: String = "ERR_CONTENT_RETIRE"
    val ARTIFACT_BASE_PATH: String = "artifactBasePath"
    val FLAGGED: String = "Flagged"
    val FLAG_DRAFT: String = "FlagDraft"
    val RETIRED: String = "Retired"
    val NODE_ID: String = "node_id"
    val VERSIONING: String = "versioning"
    val DISABLE: String = "disable"
    val LAST_STATUS_CHANGED_ON: String = "lastStatusChangedOn"
    val HIERARCHY_PREFIX: String = "hierarchy_"
    val ERR_INVALID_CONTENT: String = "ERR_INVALID_CONTENT"
    val CONTENT_OBJECT_TYPE: String = "Content"
    val LAST_UPDATED_ON: String = "lastUpdatedOn"
    val VERSION: String = "version"
    val COPY_SCHEME: String = "copyScheme"
    val CREATOR_IDS: String = "creatorIDs"
    val CREATED_BY: String = "createdBy"
    val FIELD_TO_COPY: String = "fieldsToCopy"
    val OBJECT_TYPE: String = "objectType";
    val QUESTION_SET: String = "questionset";
    val QUESTION: String = "question";
    val CREATOR: String = "creator";
    val QUESTION_SET_CAMEL_CASE: String = "questionSet";
    val SCORE_CUT_OFF_TYPE: String = "scoreCutoffType";
    val SECTIONAL_LEVEL: String = "SectionLevel";
    val DATA: String = "data"
    val NEW_CHILD_METADATA: String = "newChildMetadata";
    val NEW_CHILDREN_ID : String = "newChildrenId"
    val ASSESSMENT_LEVEL: String = "AssessmentLevel";
    val COURSE_CATEGORY: String = "courseCategory";
    val MULTILINGUAL_COURSE : String = "Multilingual Course";
    val LEARNING_RESOURCE: String = "Learning Resource";
    val REVIEWED: String = "Reviewed";
    val REVIEW_STATUS: String = "reviewStatus";
    val NAME: String = "name";
    val ID: String = "id";
    val CONTENT_EDITED: String = "CONTENT_EDITED";
    val UPDATE: String = "UPDATE";
    val SEND_TO_PUBLISH: String = "SentToPublish";
    val REVIEW: String = "Review";
    val SOURCE_COLLECTION_ID: String = "sourceCollectionId"
    val CREATED_FOR: String = "createdFor"
    val ORGANISATION: String = "organisation"
    val CREATOR_CONTACTS: String = "creatorContacts"
    val FRAMEWORK: String = "framework"
    val PREVIOUS_VERSION_COURSE_ID: String = "previousVersionCourseId"
    val CONTENT_VERSION: String = "contentVersion"
    val CONTENT_VERSION_INFO: String = "contentVersionInfo"
    val CODE: String = "code"
    val LANGUAGE: String = "language"
    val PRIMARY_CATEGORY: String = "primaryCategory"
    val POSTER_IMAGE: String = "posterImage"
    val APP_ICON: String = "appIcon"
    val CREATOR_LOGO: String = "creatorLogo"
    val CONTENT_NAME: String = "contentName"
    val STATUS_PENDING: String = "PENDING"
    val STATUS_APPROVED: String = "APPROVED"
    val STATUS_REJECTED: String = "REJECTED"
    val STATUS_RETIRED: String = "RETIRED"
    val VALID_RETIREMENT_STATUSES: Set[String] = Set(
        STATUS_PENDING,
        STATUS_APPROVED,
        STATUS_REJECTED,
        STATUS_RETIRED
    )
    val CONTENT_ID: String = "contentId"
    val REQUEST_ID: String = "requestId"
    val USER_ID_RAISED: String = "userIdRaised"
    val REASON_FOR_RETIREMENT: String = "reasonForRetirement"
    val LAST_ENROLLMENT_DATE: String = "lastEnrollmentDate"
    val RETIREMENT_DATE: String = "retirementDate"
    val REVIEWED_BY: String = "reviewedBy"
    val REVIEWED_AT: String = "reviewedAt"
    val REVIEWED_COMMENT: String = "reviewedComment"
    val ERR_INVALID_RETIREMENT_DATE:String = "ERR_INVALID_RETIREMENT_DATE";
    val ERR_LAST_ENROLLMENT_DATE: String = "ERR_LAST_ENROLLMENT_DATE";
    val ERR_CONTENT_ID_MISSING = "Missing required field: contentId.";
    val ERR_CONTENT_ID_BLANK = "contentId cannot be blank.";
    val ERR_INVALID_REASON = "ERR_INVALID_REASON";
    val ERR_MISSING_REASON = "Missing required field: reason.";
    val REASON = "reason";
    val ERR_MISSING_LAST_ENROLLMENT_DATE = "Invalid or empty lastEnrollmentDate.";
    val REASON_CANNOT_BE_EMPTY = "Reason cannot be empty.";
    val MISSING_RETIREMENT_DATE = "Missing required field: retirementDate.";
    val ERR_INVALID_RETIREMENT_DATE_MSG = "Missing required field: retirementDate.";
    val ERR_INVALID_DATE_ORDER = "ERR_INVALID_DATE_ORDER";
    val ERR_INVALID_DATE_ORDER_MSG = "retirementDate must be greater than lastEnrollmentDate."
    val ERR_CONTENT_PART_OF_COLLECTION = "ERR_CONTENT_PART_OF_COLLECTION"
    val ERR_CONTENT_PART_OF_COLLECTION_MSG = "Content cannot be retired as it is part of a collection."
    val ERR_CONTENT_HAS_ACTIVE_PLAN = "ERR_CONTENT_HAS_ACTIVE_PLAN"
    val ERR_CONTENT_HAS_ACTIVE_PLAN_MSG = "Content cannot be retired as it is part of an active learning plan."
    val SUNBIRD_COURSE_KEYSPACE = "sunbird.courses.keyspace"
    val CONTENT_RETIREMENT_RQST_TABLE = "sunbird.courses.retirement.table";
    val RETITEMENT_PRIMARY_KEY = "content_id"
    val RQST_ID = "request_id"
    val RSN_FOR_RETIREMENT = "reason_for_retirement"
    val USER_ID_RAISED_FIELD = "user_id_raised"
    val LST_ENR_DATE = "last_enrollment_date"
    val RET_DATE = "retirement_date"
    val CREATED_AT = "created_at"
    val UPDATED_AT = "updated_at"
    val APPROVED = "approved"
    val PENDING = "Pending"
    val RQST = "request"
    val MIN_RETIREMENT_GAP_DAYS = "retirement.min.gap.days"
    val MAX_RETIREMENT_GAP_DAYS = "retirement.max.gap.days"
    val CONTENT_RETIREMENT_STS = "contentRetiredStatus"
    val PENDING_APPROVAL = "PendingApproval"
    val SUNBIRD__KEYSPACE = "cbplan.lookup.keyspace"
    val CB_PLAN_LOOKUP_TABLE = "cbplan.lookup.table"
    val SUCCESS = "successful"
    val IS_VALID = "isValid"
    val MESSAGES = "messages"
    val FAILED = "Failed"
    val LANGUAGE_MAP_V1 = "languageMapV1"
    val ERR_ACTIVE_MULTILINGUAL_COURSE = "ERR_ACTIVE_MULTILINGUAL_COURSE"
    val ERR_ACTIVE_MULTILINGUAL_COURSE_MSG = "Cannot retire any course that belongs to a multilingual course with active language versions."
    val IS_BASE_LANG = "isBaseLang"
    val APPROVED_BY = "approvedBy"
    val ACTION = "action"
    val COMMENT= "comment"
    val RETIREMENT_READ_COLUMNS = "content.retirement.read.columns"
    val APPROVED_BY_RQST = "approved_by"
    val APPROVED_AT = "approved_at"
    val APPROVED_COMMENT = "approval_comment"
    val APPROVED_KEY = "Approved"
    val PENDING_RETIREMENT = "PendingRetirement"
    val APPROVE = "APPROVE"
    val REJECT = "REJECT"
    val REJECTED = "Rejected"
    val LAST_ENROLLMENT_DATE_RQST = "last_enrollment_date"
    val RETIREMENT_DATE_RQST = "retirement_date"
}
